### 前言
前端代码异常指的是以下两种情况：
- JS脚本里面存在语法错误；
- JS脚本在运行时发送错误；

捕获错误的方法：
1、try-catche方案：代码在运行时出错的时候可以在catche中被捕获。
2、window.error方案：也可以通过window.addEventListener('error', function(){err}),这个方法能捕捉到语法错误和运行时错误，同时还能知道出错的信息，以及出错的文件，行号，列号。

### try-catch
#### 原理
代码运行时出错时能在catch里被捕获。

#### 缺点
1、无法捕捉try，catch块，当前代码即使有错误，JS解析器也不会执行当前这个代码块，所以也就无法被catch。

2、没法捕捉全局的错误事件，也即是只有try，catch的块里面运行错误才会被捕捉到。

### window.error
既能捕捉语法错误，也能捕捉运行时错误。
```js
// 该方法要在页面其他js引入前最开始引入，不然无法捕捉到全部错误
window.onerror = function(msg, url, row, col, error) {
    console.log('onerror 信息如下：');
    console.log('错误信息：', msg);
    console.log('错误文件：', url);
    console.log('错误行号：', row);
    console.log('错误列号：', col);
    console.log('错误详情：', error);
}
```

#### 缺点
1、当执行的JS代码和当前站点不在同一个域名及跨域的情况下，由于浏览器的安全机制，onerror（）方法只能捕获到一个固定的错误代码Script error.

### 实例代码
```js
// 监听JS运行时异常
window.onerror = (message, source, lineNo, colNo, error) => {
    let errorMsg = wrapError({message, source, lineNo, colNo, error});
    console.log(errorMsg);
    sendErrorToServer(`JS运行异常：${errorMsg}`);
}

// 监听document资源加载异常
window.addEventListener('error', (e) => {
    let errorMsg = wrapError(e);
    sendErrorToServer(`JS运行异常：${errorMsg}`);
}, true);

// 监听未捕获的promise异常
window.addEventListener('unhandledrejection', (e) => {
    let errorMsg = wrapError(e);
    sendErrorToServer(`未捕获的promise异常：${errorMsg}`);
}, true);

// 监听最初未捕获稍后又被捕获的promise异常
window.addEventListener('rejectionhandled', (e) => {
    let errorMsg = wrapError(e);
    sendErrorToServer(`最初未捕获稍后又被捕获的promise异常：${errorMsg}`);
});

// 已捕获的promise异常
new Promise((resolve, reject) => {
    throw new Error('我被捕获了');
}).catch((e) => {
    let errorMsg = wrapError(e);
    sendErrorToServer(`已捕获的promise异常：${errorMsg}`);
});

// 未捕获的promise异常
new Promise((resolve, reject) => {
    reject('我没有被捕获');
});

// 最初未捕获稍后又被捕获的promise异常
let p1 = new Promise((resolve, reject) => {
    reject('我后来被捕获');
});

setTimeout(() => {
    p1.catch((e) => {
        console.log(e)
    });
}, 200);

function sendErrorToServer(error) {
    // 将错误上传到后台
}

function wrapError({message='', source='', lineNo='', colNo='', error, target}) {
    console.log('错误信息如下：');
    console.log('错误信息：', message);
    console.log('错误文件：', source);
    console.log('错误行号：', lineNo);
    console.log('错误列号：', colNo);
    console.log('错误详情：', error);
}
```

### 参考资源
[前端代码异常监控](http://rapheal.sinaapp.com/2014/11/06/javascript-error-monitor/)

[如何做前端异常监控？](https://www.zhihu.com/question/29953354)

[浅谈JavaScript错误](https://juejin.im/post/5b446d1ff265da0f5a253930)
